name: Destroy CDKTF Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment to destroy"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

env:
  AWS_REGION: eu-north-1

jobs:
  destroy:
    name: Destroy ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load .env.${{ inputs.environment }}
        shell: bash
        run: |
          set -a
          . .env.${{ inputs.environment }}
          set +a
          echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "CDKTF_BACKEND_BUCKET=$CDKTF_BACKEND_BUCKET" >> $GITHUB_ENV
          echo "CDKTF_BACKEND_KEY=$CDKTF_BACKEND_KEY" >> $GITHUB_ENV
          echo "CDKTF_BACKEND_LOCK_TABLE=$CDKTF_BACKEND_LOCK_TABLE" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Install CDKTF & dependencies
        run: |
          npm install --global cdktf-cli
          pip install -r requirements.txt
          cdktf get

      - name: Destroy infrastructure (no confirmation)
        run: cdktf destroy --auto-approve
